"""empty message

Revision ID: 424313534f0e
Revises: 0626d573d696
Create Date: 2025-06-30 12:32:41.343238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424313534f0e'
down_revision = '0626d573d696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=266),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=266),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))

    # ### end Alembic commands ###
